import { IImageDesignGroupProps } from '../types/PortfolioType';

export const ImageDesignGroup: IImageDesignGroupProps[] = [
  {
    src: '/images/design26/popup/260608_pop.png',
    type: '팝업',
    direction: 'vertical',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/AIblog.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/event/5event.png',
    type: '이벤트',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/event/5friend.png',
    type: '이벤트',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  
    
  {
    src: '/images/design26/event/5event2.png',
    type: '이벤트',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/인스타그램 사업설명회_1.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/인스타그램 사업설명회_2.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/26_6_0.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  
  {
    src: '/images/design26/popup/26_6_2.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/26_6_3.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/26_6_4.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/26_6_5.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/thub.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  
  {
    src: '/images/design26/popup/엘리아드림_1.png',
    type: '이벤트',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  
  
  {
    src: '/images/design26/popup/엘리아드림_2.png',
    type: '이벤트',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/엘리아드림_3.png',
    type: '이벤트',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/엘리아드림_4.png',
    type: '이벤트',
    direction: 'horizontal',
    title: '엘리아영어',
  },

  {
    src: '/images/design26/popup/엘리아드림_5.png',
    type: '이벤트',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/insta1.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/insta2.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
    {
    src: '/images/design26/popup/insta3.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
    {
    src: '/images/design26/popup/insta4.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/insta5.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/insta7.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/insta9.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },

  {
    src: '/images/design26/popup/insta6.png',
    type: '상세',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  
  
  {
    src: '/images/design26/popup/insta8.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/sb.png',
    type: '이벤트',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/6presentation.png',
    type: '팝업',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/promotion.png',
    type: '팝업',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  
  {
    src: '/images/design26/popup/HS_presentation.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/HS_presentation_1.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/HS_presentation_2.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/HS_presentation_3.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/HS_presentation_4.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },

  {
    src: '/images/design26/popup/card_chun.png',
    type: '팝업',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/chung.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/강서등촌 친구소개 이벤트.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/강서등촌 파닉스 홍보.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/스피치 콘테스트 배너.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/오산세교 친구소개 할인 이벤트.png',
    type: '이벤트',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/오산세교 파닉스 신규생 이벤트.png',
    type: '이벤트',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/용인외대부고탐방.png',
    type: '상세',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/용인외대부고탐방_오시는길.png',
    type: '상세',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/학부모설명회-1.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/popup/학부모설명회-2.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '엘리아영어',
  },


  
  {
    src: '/images/design26/banner/265_2.png',
    type: '배너',
    direction: 'vertical',
    title: '엘리아영어',
  },

  {
    src: '/images/design26/banner/banner_elea.png',
    type: '긴배너',
    direction: 'vertical',
    title: '엘리아영어',
  },
  
  {
    src: '/images/design26/banner/banner_1.png',
    type: '긴배너',
    direction: 'vertical',
    title: '패스트트랙',
  },
  {
    src: '/images/design26/banner/banner_2.png',
    type: '긴배너',
    direction: 'vertical',
    title: '패스트트랙',
  },
  {
    src: '/images/design26/banner/banner_3.png',
    type: '긴배너',
    direction: 'vertical',
    title: '패스트트랙',
  },

  {
    src: '/images/design26/etc/back1.png',
    type: '긴배너',
    direction: 'vertical',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/etc/back2.png',
    type: '긴배너',
    direction: 'vertical',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/etc/back3.png',
    type: '긴배너',
    direction: 'vertical',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/etc/back4.png',
    type: '긴배너',
    direction: 'vertical',
    title: '엘리아영어',
  },
  
  {
    src: '/images/design26/etc/fast1.png',
    type: '상세',
    direction: 'vertical',
    title: '패스트트랙',
  },
  {
    src: '/images/design26/etc/fast2.png',
    type: '상세',
    direction: 'vertical',
    title: '패스트트랙',
  },
  {
    src: '/images/design26/etc/fast3.png',
    type: '상세',
    direction: 'vertical',
    title: '패스트트랙',
  },
  {
    src: '/images/design26/etc/fast5.png',
    type: '상세',
    direction: 'vertical',
    title: '패스트트랙',
  },
  {
    src: '/images/design26/etc/fast4.png',
    type: '상세',
    direction: 'vertical',
    title: '패스트트랙',
  },

  {
    src: '/images/design26/etc/엘리아 멤버십_1.png',
    type: '기타',
    direction: 'vertical',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/etc/엘리아 멤버십_2.png',
    type: '기타',
    direction: 'vertical',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/etc/엘리아 멤버십_3.png',
    type: '기타',
    direction: 'vertical',
    title: '엘리아영어',
  },
  {
    src: '/images/design26/etc/엘리아 멤버십_4.png',
    type: '기타',
    direction: 'vertical',
    title: '엘리아영어',
  },

  
  
  {
    src: '/images/design26/popup/card_fc4.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '외대HS',
  },
  {
    src: '/images/design26/popup/card_fc2.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '외대HS',
  },
  {
    src: '/images/design26/popup/card_fc5.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '외대HS',
  },
  {
    src: '/images/design26/popup/card_fc1.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '외대HS',
  },
  {
    src: '/images/design26/popup/card_fc3.png',
    type: '카드뉴스',
    direction: 'horizontal',
    title: '외대HS',
  },
  // 썸네일, 엘리아멤버십,
  
  {
    src: '/images/design/detail/왜바른보정인가.jpg',
    type: '상세',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/detail/주문방법.jpg',
    type: '상세',
    direction: 'horizontal',
    title: '바른보정',
  },
  {
    src: '/images/design/detail/nature.jpg',
    type: '상세',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/detail/정리및보정.jpg',
    type: '상세',
    direction: 'vertical',
    title: '바른보정',
  },

  {
    src: '/images/design/detail/구매전_5.jpg',
    type: '상세',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/detail/20230110_모집공고.png',
    type: '이벤트',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/detail/가정의달_2.png',
    type: '이벤트',
    direction: 'horizontal',
    title: '바른보정',
  },
  {
    src: '/images/design/detail/고급사진보정.jpg',
    type: '상세',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/detail/buy_tip.png',
    type: '상세',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/detail/dyson_mo_done.jpg',
    type: '이벤트',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/detail/levelup_pc1.png',
    type: '상세',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/detail/make_tip.png',
    type: '상세',
    direction: 'horizontal',
    title: '바른보정',
  },
  {
    src: '/images/design/detail/maker_service.png',
    type: '상세',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/detail/model_pc_1.jpg',
    type: '이벤트',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/popup/221115_popup.jpg',
    type: '팝업',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/banner/기업구매-메인배너.png',
    type: '배너',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/banner/메인배너-방문수령_2.jpg',
    type: '배너',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/banner/change_frame.png',
    type: '팝업',
    direction: 'vertical',
    title: '바른보정',
  },

  {
    src: '/images/design/banner/main0.png',
    type: '배너',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/banner/main_thumb.png',
    type: '배너',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/banner/221212_main_4.jpg',
    type: '배너',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/banner/main_baby.jpg',
    type: '배너',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/detail/turnframe.png',
    type: '상세',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/detail/premium2_mo.jpg',
    type: '상세',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/banner/mo_main.png',
    type: '팝업',
    direction: 'horizontal',
    title: '바른보정',
  },
  {
    src: '/images/design/banner/editorplus.jpg',
    thumb: '/images/design/banner/thumbplus.png',
    type: '팝업',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/detail/가정의달_10.jpg',
    type: '팝업',
    direction: 'horizontal',
    title: '바른보정',
  },
  {
    src: '/images/design/event/상품베이비썸네일_1.jpg',
    type: '썸네일',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/event/상품썸네일_3.jpg',
    type: '썸네일',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/event/썸네일_1.jpg',
    type: '썸네일',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/event/썸네일_2.jpg',
    type: '썸네일',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/event/감사영상_3.jpg',
    type: '썸네일',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/event/감사영상_4)11.jpg',
    type: '썸네일',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/event/pro_mode.jpg',
    thumb: '/images/design/event/thumbeditor.png',
    type: '썸네일',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/event/사진보정_구매방법.jpg',
    type: '기타',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/event/event_banner_mo.jpg',
    type: '이벤트',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/event/영상문의_업로드관련.jpg',
    type: '기타',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/event/new액자.jpg',
    type: '이벤트',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/popup/230131_pop.png',
    type: '팝업',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/popup/230407_2.png',
    type: '팝업',
    direction: 'horizontal',
    title: '바른보정',
  },
  {
    src: '/images/design/popup/230502_pop.png',
    type: '팝업',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/popup/230601_pop_2.png',
    type: '팝업',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/popup/230630_pop.png',
    type: '팝업',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/popup/230922_banner.jpg',
    type: '팝업',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/popup/231213_pop.jpg',
    type: '팝업',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/popup/전기점검안내.png',
    type: '팝업',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/popup/추석.jpg',
    type: '팝업',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/popup/pop.jpg',
    type: '이벤트',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/popup/parent_pop2.jpg',
    type: '팝업',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/addpicture/newblackbig1_n.jpg',
    thumb: '/images/design/addpicture/thumbadd.png',
    type: '합성',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/addpicture/realacrle.jpg',
    type: '합성',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/addpicture/black.jpg',
    type: '합성',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/addpicture/diasec.jpg',
    type: '합성',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/addpicture/필모션카드.jpg',
    type: '합성',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/etc/etcmain.png',
    thumb: '/images/design/etc/thumb_etc.png',
    type: '기타',
    direction: 'vertical',
    title: '바른보정',
  },
  {
    src: '/images/design/banner/img0.jpg',
    thumb: '/images/design/banner/thumbimg0.png',

    type: '기타',
    direction: 'vertical',
    title: '바른보정',
  },
];
