import type { Metadata } from 'next';
import './globals.css';
import StyledComponentsRegistry from '@/app/lib/registry';
import { NanumNeo, montserrat, pretendard } from '../public/fonts/fonts';
import { ThemeProvider } from '@/provider/ThemeProvider';
import PageTransition from './components/commons/Pagetransition';
import Header from './components/Layout/Header';

export const metadata: Metadata = {
  title: '준모 포트폴리오',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={`${NanumNeo.variable} ${pretendard.variable} ${montserrat.className} `}>
      <StyledComponentsRegistry>
        <body className={NanumNeo.className} style={{ overflowX: 'hidden' }}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
